- name: Download fie - Fetchin the Repo
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo
    dest: /etc/yum.repos.d/{Component}.repo

- name: Install Mongodb in Box
  ansible.builtin.yum:
    name: mongodb-org
    state: present
  ignore_errors: true

- name: enable and starting the mongodb
  ansible.builtin.service:
    name: mongod 
    state: started
    enabled: true


- name: Replace 127.0.0.1/0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart the mongodb
  ansible.builtin.service:
    name: mongod 
    state: restarted

- name: Recursively remove directory
  ansible.builtin.file:
    path: /tmp/mongodb-main
    state: absent

- name: Recursively remove directory
  ansible.builtin.file:
    path: 
     - /tmp/mongodb.zip
     - /tmp/mongodb
    state: absent











# echo " cleanup before installation"
# rm -rf /tmp/mongodb.zip
# rm -rf /tmp/mongodb-main &>>${Logfile}
# StatusCheck $?

# echo "Download the Zip file MongoDB"
# curl -s -L -o /tmp/mongodb.zip "https://github.com/roboshop-devops-project/mongodb/archive/main.zip" &>>${Logfile}
# StatusCheck $?

# cd /tmp
# unzip mongodb.zip &>>${Logfile}
# StatusCheck $?

# cd mongodb-main &>>${Logfile}
# StatusCheck $?
# mongo < catalogue.js &>>${Logfile}
# StatusCheck $?
# mongo < users.js &>>${Logfile}
# StatusCheck $?



