
- name: Remove Nginx package from Box
  ansible.builtin.yum:
    name: nginx 
    state: absent
  ignore_errors: true 

- name: Recursively remove directory
  ansible.builtin.file:
    path: /etc/nginx/*
    state: absent

- name: Install Nginx package in Box
  ansible.builtin.yum:
    name: nginx 
    state: present
  ignore_errors: true

- name: enable and starting the nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true


- name: Download file
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent
   
- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

# echo "------------Let's download the HTDOCS content and deploy under the Nginx path----"
# curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip" &>>${Logfile}
# StatusCheck $?



# echo "----------Deploy the downloaded content in Nginx Default Location.------"

# cd /usr/share/nginx/html &>>${Logfile}
# StatusCheck $?
# rm -rf * 
# unzip /tmp/frontend.zip &>>${Logfile}
# StatusCheck $?
# mv frontend-main/static/* . &>>${Logfile}
# StatusCheck $?
# mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf &>>${Logfile}
# StatusCheck $?


# echo " Updating the systemD service file with DNS name"
# sed -i -e '/catalogue/ s/localhost/catalogue.Roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${Logfile}
# StatusCheck $?
# sed -i -e '/user/ s/localhost/user.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${Logfile}
# StatusCheck $?
# sed -i -e '/cart/ s/localhost/cart.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${Logfile}
# StatusCheck $?
# sed -i -e '/shipping/ s/localhost/shipping.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${Logfile}
# StatusCheck $?
# sed -i -e '/payment/ s/localhost/payment.roboshop.internal/'  /etc/nginx/default.d/roboshop.conf &>>${Logfile}
# StatusCheck $?



# echo "--------------Finally restart the service once to effect the changes.--------------"
# systemctl restart nginx &>>${Logfile}
# StatusCheck $?



